//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Key]
        public int UserId { get; set; }

        [Display(Name="User Name")]
        [Required(ErrorMessage="User name is required")]
        [StringLength(60,MinimumLength=3,ErrorMessage="Minimum length is 3")]
        public string UserName { get; set; }

        [Display(Name="Full Name")]
        [Required(ErrorMessage="Full Name is required")]
        public string FullName { get; set; }

        [Required(ErrorMessage="Password is required")]
        [DataType(DataType.Password)]
        [StringLength(8,MinimumLength=5)]
        public string Password { get; set; }

        [Required(ErrorMessage="EmailID is required")]
        [EmailAddress(ErrorMessage="Invalid EmailAddress")]
        public string EmailID { get; set; }
    }
}
